# Generated by Django 4.1.6 on 2023-04-08 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('b', 'boolean'), ('e', 'enum'), ('s', 'string'), ('n', 'number'), ('d', 'datetime')], max_length=1)),
                ('value', models.CharField(default=None, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='assignee',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tag')),
            ],
        ),
    ]
