# Generated by Django 4.1.6 on 2023-04-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tag_solution_assignee_solution_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='value',
        ),
        migrations.CreateModel(
            name='TagValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=None, max_length=1000, null=True)),
                ('facilities', models.ManyToManyField(to='app.facility')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.tag')),
            ],
        ),
    ]
