# Generated by Django 4.1.6 on 2023-04-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_tag_value_tagvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagvalue',
            name='facilities',
        ),
        migrations.AddField(
            model_name='tagvalue',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facility'),
        ),
    ]
