# Generated by Django 4.1.6 on 2023-04-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tagvalue_facilities_tagvalue_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagvalue',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tag'),
        ),
    ]
