# Generated by Django 4.1.6 on 2023-04-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tagvalue_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='media',
        ),
        migrations.AddField(
            model_name='tag',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.facility')),
            ],
        ),
    ]
