# Generated by Django 4.1.6 on 2023-04-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_facility_media_tag_required_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('p', 'pictures'), ('d', 'documents')], default='p', max_length=1),
        ),
    ]
