# Generated by Django 4.1.6 on 2023-04-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_facility_work_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('n', 'нет поручений'), ('с', 'закрыт'), ('w', 'в работе'), ('d', 'просрочен')], default='n', max_length=1)),
                ('deadline', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=2000)),
                ('assignee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.workgroup')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.facility')),
            ],
        ),
    ]
