# Generated by Django 4.1.6 on 2023-04-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_manager_name_alter_assignment_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
