# Generated by Django 4.1.6 on 2023-04-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_assignment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignee',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='facility',
            name='next_meeting_date',
            field=models.DateTimeField(null=True),
        ),
    ]
