# Generated by Django 4.1.6 on 2023-04-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_assignment_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.assignment'),
        ),
        migrations.AddField(
            model_name='media',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.solution'),
        ),
        migrations.AlterField(
            model_name='media',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facility'),
        ),
    ]
