# Generated by Django 4.1.6 on 2023-04-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_manager_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
