# Generated by Django 4.1.6 on 2023-04-10 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_workgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='work_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='app.workgroup'),
            preserve_default=False,
        ),
    ]
