services:
  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    environment:
      PROXY_HOST: http://backend:8000
    ports:
      - "3000:3000"
    links:
      - backend
